name: Build Telegram Desktop

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            cmake \
            g++ \
            libglib2.0-dev \
            libssl-dev \
            qt6-base-dev \
            qt6-tools-dev \
            qt6-tools-dev-tools \
            liblzma-dev \
            zlib1g-dev \
            libminizip-dev

      - name: Configure CMake
        run: cmake -S tdesktop -B build

      - name: Build
        run: cmake --build build --parallel
