name: Build Telegram Desktop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential pkg-config qtbase5-dev qttools5-dev-tools libssl-dev

      - name: Configure and build
        run: |
          cmake -S tdesktop -B build
          cmake --build build --config Release
